# Generated by Django 5.2 on 2026-03-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaosConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('MEMORY_LEAK', 'Memory Leak'), ('NETWORK_LATENCY', 'Network Latency'), ('ERROR_RAIN', 'Error Rain')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChaosEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('MEMORY_LEAK', 'Memory Leak'), ('NETWORK_LATENCY', 'Network Latency'), ('ERROR_RAIN', 'Error Rain')], max_length=20)),
                ('event_type', models.CharField(choices=[('INJECTED', 'Chaos Injected'), ('STOPPED', 'Chaos Stopped'), ('INCIDENT_CREATED', 'Incident Created')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaos_events', to='tasks.task')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
